reddit_clone/config/routes.rb
Rails.application.routes.draw do
resources :users 
resource :session 
resources :subs
resources :posts do
  resources :comments, only: [:new]
end
resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author,
    foreign_key: :user_id,
    primary_key: :id,
    class_name: 'User'
    
  belongs_to :post
  
  belongs_to :parent_comment, optional: true,
  primary_key: :id, 
  foreign_key: :parent_comment_id, 
  class_name: :Comment 
  
  has_many :child_comments, 
  primary_key: :id,
  foreign_key: :parent_comment_id, 
  class_name: :Comment 
  
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  
  has_many :post_subs, inverse_of: :post
  
  has_many :comments
  
  has_many :subs, 
  through: :post_subs, 
  source: :sub
  
  belongs_to :user 

end

reddit_clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  
  validates :post, :sub_id, presence: true 
  
  belongs_to :post
  belongs_to :sub 
end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true
  belongs_to :user

  has_many :post_subs
  
  has_many :posts, 
  through: :post_subs, 
  source: :post
end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  session_token   :string
#  username        :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  after_initialize :ensure_session_token
  validates :username, uniqueness: true
  validates :session_token, :username, presence: true 
  validates :password, length: {minimum: 6, allow_nil: true }
  
  has_many :subs
  has_many :posts 
  has_many :comments
  
  attr_reader :password 
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil 
  end 
  
  def ensure_session_token 
    self.session_token ||= User.generate_session_token
  end 
  
  def reset_session_token 
    self.session_token = User.generate_session_token
    self.save! 
    self.session_token 
  end 
  
  def password=(password)
    @password = password 
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end 
  
end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :logged_in?
  
  def current_user 
    current_user = User.find_by(session_token: session[:session_token])
  end 
  
  def logged_in?
    !!current_user
  end 
  
  def ensure_login 
    redirect_to new_session_url unless logged_in? 
  end 
end

reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new 
    @post_id = params[:post_id]  
  end 
  
  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages 
      redirect_to post_url(params[:post_id])
    end 
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  
  private 
  def comment_params 
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end 
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
  
    if @post.save 
      redirect_to post_url(@post)
    else 
      flash.now[:errors] = @post.errors.full_messages 
      render :new 
    end 
  end

  def edit
    @subs = Sub.all
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    
    if @post.update(post_params)
      redirect_to post_url(@post)
    else 
      flash.now[:errors] = @post.errors.full_messages
      render :edit 
    end 
  end

  def destroy
    post = Post.find(params[:id])
    if post 
      post.delete 
      redirect_to subs_url 
    end 
  end
  
  private 
  
  def post_params 
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end 
end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    
    if user 
      session[:session_token] = user.reset_session_token
      redirect_to subs_url
    else 
      flash.now[:errors] = ["Invalid Login Info"]
      render :new 
    end 
  end

  def destroy
    current_user.reset_session_token
    session[:session_token] = nil 
    redirect_to new_session_url
  end
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :is_mod?, only: [:edit, :update]
  
  def new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id 
    if @sub.save 
      redirect_to sub_url(@sub)
    else 
      flash.now[:errors] = @sub.errors.full_messages 
      render :new 
    end 
  end

  def index
    @subs = Sub.all 
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    
    if @sub && @sub.update(sub_params) #update_attributes ?? 
      redirect_to sub_url(@sub) 
    else 
      flash.now[:errors] = @sub.errors.full_messages 
      render :edit 
    end 
  end
  
  def is_mod?
    sub_forum = Sub.find(params[:id])
    
    unless current_user.id == sub_forum.user_id
      redirect_to new_session_url
    end
  end
  
   private 
  
  def sub_params 
    params.require(:sub).permit(:title, :description)
  end   
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    
  end

  def create
    user = User.new(user_params)
    if user.save 
      session[:session_token] = user.reset_session_token

      redirect_to subs_url
    else 
      flash.now[:errors] = user.errors.full_messages 
      render :new 
    end 
  end
  
  
  
  
  private 
  def user_params 
    params.require(:user).permit(:username, :password)
  end 
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

reddit_clone/app/helpers/subs_controller_helper.rb
module SubsControllerHelper
end

reddit_clone/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

reddit_clone/app/views/comments/_comment.html.erb
<ul>
  <li>
    <% comments.each do |comment| %>
      <% if comment.parent_comment_id == parent.id %>
        <p><%= comment.content %></p>
        <a href="<%= comment_url(comment) %>">Reply</a>
          <%= render 'comments/comment', comments: comments, parent: comment %>
        <% end %>
    <% end %>
  </li>
</ul>

reddit_clone/app/views/comments/new.html.erb
<h1>New Comment</h1>

<form  action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <input type="hidden" name="comment[post_id]" value="<%=@post_id%>">
  
  <label>Comment
    <input type="textarea" name="comment[content]" >
  </label>
  
  
  <input type="submit" name="" value="Create Comment">
</form>

reddit_clone/app/views/comments/show.html.erb
<h1>Comment</h1>

<%= @comment.content %>

<h3>Reply</h3>

<form  action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <label>Content
    <input type="textarea" name="comment[content]" value="">
  </label>
  
  <input type="submit" name="" value="Reply">
</form>

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:errors] %>
    <% if !logged_in? %>
      <%= button_to 'Login', new_session_url, method: :get %>
      <%= button_to 'Sign Up', new_user_url, method: :get %>
    <% else %>
      <%= button_to 'Sign Out', session_url, method: :delete %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form  action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  
  <label>URL 
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  
  <label>Content 
    <textarea name="post[content]" rows="8" cols="80"><%= @post.content %></textarea>
  </label>
  <input type="hidden" name="post[sub_ids][]" value="">
  
  <% @subs.each do |subbs| %>
  <input type="checkbox" name="post[sub_ids][]" value="<%=subbs.id%>" <%= @post.subs.include?(subbs) ? "checked" : "" %>><%= subbs.title %>
  <% end %>
  
  <input type="submit" name="" value="Update Post">
</form>

reddit_clone/app/views/posts/new.html.erb
<h1>New Post</h1>

<form  action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="post[title]" value="">
  </label>
  
  <label>URL 
    <input type="text" name="post[url]" value="">
  </label>
  
  <label>Content 
    <textarea name="post[content]" rows="8" cols="80"></textarea>
  </label>
  
  <% @subs.each do |subbs| %>
  <input type="checkbox" name="post[sub_ids][]" value="<%=subbs.id%>"><%= subbs.title %>
  <% end %>
  
  <input type="submit" name="" value="Create Post">
</form>

reddit_clone/app/views/posts/show.html.erb
<%= @post.title %>
<%= @post.url %>
<%= @post.content %>
<%= @post.user.username %>

<% @comments = @post.comments %>

<% @comments.each do |comment| %>
  <% if comment.parent_comment_id.nil? %>
      <p><%= comment.content %></p>
      <a href="<%= comment_url(comment) %>">Reply</a> 
    <%= render 'comments/comment', comments: @comments, parent: comment %>
  <% end %>
<% end %>

<br>
<%= link_to "Comment", new_post_comment_url(@post), method: :get %>

reddit_clone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form  action="<%= sub_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>
  
  <label>Description 
    <input type="text" name="sub[description]" value="<%=@sub.description%>">
  </label>
  
  <input type="submit" name="" value="Update Sub">
</form>

reddit_clone/app/views/subs/index.html.erb
<% @subs.each do |sub_forum| %>
<%= link_to sub_forum.title, sub_url(sub_forum) %>
<% end %>

reddit_clone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form  action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>
  
  <label>Description 
    <input type="text" name="sub[description]" value="">
  </label>
  
  <input type="submit" name="" value="Create Sub">
</form>

reddit_clone/app/views/subs/show.html.erb
<%= @sub.title %>
<%= @sub.description %>
<% @sub.posts.each do |post| %>
<%= link_to post.title, post.url %>
<% end  %>

reddit_clone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  
  <input type="submit" name="" value="Sign Up">
</form>